services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    networks:
      - laravel_network
    volumes:
      - .:/var/www/html
    depends_on:
      - laravel-db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: laravel-db
      DB_PORT: 3306
      DB_DATABASE: news_aggregator_db
      DB_USERNAME: root
      DB_PASSWORD: root

  laravel-db:
    image: mysql:8.0
    container_name: laravel-db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Only root password
      MYSQL_DATABASE: news_aggregator_db  # The database name
    networks:
      - laravel_network
    volumes:
      - db_data:/var/lib/mysql

networks:
  laravel_network:
    driver: bridge

volumes:
  db_data:
